### ISSUE TITLE
submission stuff

### ISSUE THREAD

**Issue by teixeirak** [forc-db/Global_Productivity#130]
@beckybanbury , here's a running list of what we need:

- [ ]  Please supply a 100 word non-technical summary of your work that we may use to promote your article. The summary should allow readers to quickly gain an understanding of the most important aspect of your paper. The image should clearly represent the work described in the paper (eg a diagram or illustration selected from the manuscript or an additional "eye-catching" figure). 
- [x]  social media handles
- [x] ensure adherence to submission checklist

**Comment by teixeirak** [comment]
@beckybanbury , I think Fig. 2 is definitely the best for the graphical abstract. If you'd like to draft the 100 word summary, please do so. I'll put in a placeholder if needed.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/6355854/109231772-2a649780-7795-11eb-80eb-324ecc526eb1.png">

**Comment by teixeirak** [comment]
@beckybanbury , the acceptance email has a checklist of formatting requirements, now loaded [here](https://github.com/forc-db/Global_Productivity/blob/master/manuscript/Attached%20standard%20file-%20*%20GCB-accepted-submission-checklist-Nov-2020.pdf). We need to work through these, including converting manuscript and tables to Word.

**Comment by beckybanbury** [comment]
@teixeirak am I correct that SI tables do not need formatting in word + we can just submit the SI as it is?

**Comment by teixeirak** [comment]
> @teixeirak am I correct that SI tables do not need formatting in word + we can just submit the SI as it is?

Correct-- just the main manuscript. The SI will stay formatted exactly as we submit it.

**Comment by beckybanbury** [comment]
I've done the two manuscript tables in word format + saved in manuscript folder.

For figures it states that for multi panel figures panels need to be labelled in bold (a) (b) etc - all plots now have these labels but I can't figure out how to get them in bold. Any ideas?

**Comment by teixeirak** [comment]
> I've done the two manuscript tables in word format + saved in manuscript folder.

Wonderful; thanks! I'll look at this soon.



> For figures it states that for multi panel figures panels need to be labelled in bold (a) (b) etc - all plots now have these labels but I can't figure out how to get them in bold. Any ideas?

I'm definitely not the person to ask about manipulating R!  If you can't do it easily, I wouldn't worry about it. They may fix it, or if not they'll send the figure back to us to fix.

**Comment by teixeirak** [comment]
@beckybanbury , here's a draft summary (entered as a placeholder):

We synthesize global data on how forest carbon fluxes vary globally with respect to climate and one another. Rates of C cycling increased continuously and in proportion to one another with decreasing latitude, increasing temperature, or decreasing temperature seasonality. This synthesis provides a foundation for understanding global patterns in forest C cycling in an era when forests will play a critical yet uncertain role in shaping Earth’s rapidly changing climate.

I think it has a lot of room for improvement if you'd like to take a stab at it.

**Comment by teixeirak** [comment]
@beckybanbury , we need the main manuscript figures  PNG, JPEG, or WEBP

**Comment by teixeirak** [comment]
@beckybanbury , CORRECTION: figures need to be  .jpg, .tif, or .eps.

**Comment by teixeirak** [comment]
The graphical abstract needs to be PNG, JPEG, or WEBP, so if you save the figures as .tif or .eps, we'll need to keep the .png version of Fig. 2

**Comment by beckybanbury** [comment]
@teixeirak thanks for catching that - I'll work on them now

**Comment by beckybanbury** [comment]
@teixeirak sorry that took way longer than I anticipated - all figures for the main manuscript are now also in jpeg format

**Comment by beckybanbury** [comment]
@teixeirak The word file for the manuscript looks good! I'm a little confused from the guidelines as to whether we need to insert figure + table captions and placements into this file - do you know?

**Comment by teixeirak** [comment]
I don't think so.

Thanks for the figures. I'll get back to the submission in a little bit.

**Comment by teixeirak** [comment]
@beckybanbury , let me know if you have any photos you'd like to include for social media/ candidate journal cover.

**Comment by beckybanbury** [comment]
@teixeirak I don't have much to change on that summary. I've removed one of the two 'global(ly)'s from the first sentence, and added a sentence (which I'm happy for you to change):

We synthesize global data on how forest carbon fluxes vary with respect to climate and one another. Rates of C cycling increased continuously and in proportion to one another with decreasing latitude, increasing temperature, or decreasing temperature seasonality. The effects of temperature were modified by water availability, and carbon fluxes were reduced under hot and dry conditions. This synthesis provides a foundation for understanding global patterns in forest C cycling in an era when forests will play a critical yet uncertain role in shaping Earth’s rapidly changing climate.

I don't think I have any photos!

**Comment by beckybanbury** [comment]
Great, thanks!
